In [1]:
import numpy as np

# 1D Array

In [2]:
sq = np.array([0, 1, 4, 9, 16, 25])

In [3]:
sq

array([ 0,  1,  4,  9, 16, 25])

In [4]:
sq.shape

(6,)

# Selecting Entries

In [5]:
sq[0]

0

In [6]:
sq[5]

25

In [7]:
sq[3]

9

# Slicing

In [12]:
sq

array([ 0,  1,  4,  9, 16, 25])

In [8]:
sq[0:3]

array([0, 1, 4])

In [9]:
sq[:3]

array([0, 1, 4])

In [10]:
sq[3:]

array([ 9, 16, 25])

In [11]:
sq[:]

array([ 0,  1,  4,  9, 16, 25])

# 2D Arrays

In [18]:
sq = np.array([[0, 1, 2, 3, 4, 5],
               [0, 1, 4, 9, 16, 25],
               [2, 2, 1, 2, 2, 1],
               [1, -1, 1, -1, 1, -1]
              ])

In [19]:
sq

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  1,  4,  9, 16, 25],
       [ 2,  2,  1,  2,  2,  1],
       [ 1, -1,  1, -1,  1, -1]])

In [20]:
sq.shape

(4, 6)

# Selecting Entries

In [22]:
sq[1,3]
sq[2,4]

2

# Slicing 2D Arrays

In [ ]:
sq

In [ ]:
sq[1:3, 2:5]

In [24]:
sq[:,0]

array([0, 0, 2, 1])

In [23]:
sq[2,:]

array([2, 2, 1, 2, 2, 1])